import bcrypt from 'bcryptjs';

const data = {
	users: [
		{
			name: 'John',
			email: 'admin@example.com',
			password: bcrypt.hashSync('123456'),
			isAdmin: true,
		},
		{
			name: 'Vania Valensia',
			email: 'vaniavalensia23@gmail.com',
			password: bcrypt.hashSync('kurumikurumi'),
			isAdmin: true,
		},
		{
			name: 'Ari Sudana',
			email: 'arisudana114@gmail.com',
			password: bcrypt.hashSync('Risingsun1'),
			isAdmin: true,
		},
	],
	products: [
		{
			id: 'omid-0000001',
			name: 'Roasted Almonds',
			slug: 'roasted-almonds',
			categorySlug: 'nuts',
			quantity: [300, 500, 1000],
			price: [51000, 79000, 151000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/yJ0dMLp.jpg',
				'https://i.imgur.com/roasted-almonds2.jpeg',
				'https://i.imgur.com/roasted-almonds3.jpeg',
			],
			description: 'Extra crunchy roasted Californian Almonds.',
			isAvailable: true,
			isDiscount: true,
			discount: 20,
			isFeatured: true,
		},
		{
			id: 'omid-0000002',
			name: 'Roasted Pistachios',
			slug: 'roasted-pistachios',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [125000, 235000, 449000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/TGh53JL.jpg',
				'https://i.imgur.com/roasted-pistachios2.jpeg',
				'https://i.imgur.com/roasted-pistachios3.jpeg',
			],
			description: 'Extra crunchy roasted Californian Pistachios.',
			isAvailable: true,
			isDiscount: true,
			discount: 10,
			isFeatured: true,
		},
		{
			id: 'omid-0000003',
			name: 'Roasted Walnuts',
			slug: 'roasted-walnuts',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [38000, 72000, 140000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/xTZdf3j.jpg',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Extra crunchy roasted Walnut kernels',
			isAvailable: true,
			isDiscount: true,
			discount: 15,
			isFeatured: true,
		},
		{
			id: 'omid-0000004',
			name: 'Dried Cranberries',
			slug: 'dried-cranberries',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/vLwCsUr.jpg',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Dried Cranberries',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
	],
};

export default data;
