import bcrypt from 'bcryptjs';

const data = {
	users: [
		{
			name: 'John',
			email: 'admin@example.com',
			password: bcrypt.hashSync('123456'),
			isAdmin: true,
		},
		{
			name: 'Vania Valensia',
			email: 'vaniavalensia23@gmail.com',
			password: bcrypt.hashSync('kurumikurumi'),
			isAdmin: true,
		},
		{
			name: 'Ari Sudana',
			email: 'arisudana114@gmail.com',
			password: bcrypt.hashSync('Risingsun1'),
			isAdmin: true,
		},
	],
	products: [
		{
			id: 'omid-0000001',
			name: 'Roasted Almonds',
			slug: 'roasted-almonds',
			categorySlug: 'nuts',
			quantity: [300, 500, 1000],
			price: [51000, 79000, 151000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/yJ0dMLp.jpg',
				'https://i.imgur.com/roasted-almonds2.jpeg',
				'https://i.imgur.com/roasted-almonds3.jpeg',
			],
			description: 'Extra crunchy roasted Californian Almonds.',
			isAvailable: true,
			isDiscount: true,
			discount: 20,
			isFeatured: true,
		},
		{
			id: 'omid-0000002',
			name: 'Roasted Pistachios',
			slug: 'roasted-pistachios',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [125000, 235000, 449000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/TGh53JL.jpg',
				'https://i.imgur.com/roasted-pistachios2.jpeg',
				'https://i.imgur.com/roasted-pistachios3.jpeg',
			],
			description: 'Extra crunchy roasted Californian Pistachios.',
			isAvailable: true,
			isDiscount: true,
			discount: 10,
			isFeatured: true,
		},
		{
			id: 'omid-0000003',
			name: 'Roasted Walnuts',
			slug: 'roasted-walnuts',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [38000, 72000, 140000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/xTZdf3j.jpg',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Extra crunchy roasted Walnut kernels',
			isAvailable: true,
			isDiscount: true,
			discount: 15,
			isFeatured: true,
		},
		{
			id: 'omid-0000004',
			name: 'Dried Cranberries',
			slug: 'dried-cranberries',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/vLwCsUr.jpg',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Dried Cranberries',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000005',
			name: 'Dried Blueberries',
			slug: 'dried-blueberries',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/nyjcngF.jpg',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Dried Blueberries',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: true,
		},
		// NEW PRODUCTS TO BE ADDED
		{
			id: 'omid-0000006',
			name: 'Dried Apricots',
			slug: 'dried-apricots',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/9DlJWYd.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Dried Apricots',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000007',
			name: 'Prunes',
			slug: 'prunes',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/N7f83B7.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Prunes',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000008',
			name: 'Roasted Macadamias',
			slug: 'roasted-macadamias',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/d5tK73S.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Imported style 0 Australian Macadamias',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: true,
		},
		{
			id: 'omid-0000009',
			name: 'Raw Pecans',
			slug: 'raw-pecans',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/0GOsYuG.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Pecans',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: true,
		},
		{
			id: 'omid-0000010',
			name: 'Raw Macadamias',
			slug: 'raw-macadamias',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/yqCMMmR.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Macadamias',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000011',
			name: 'Roasted Hazelnuts',
			slug: 'roasted-hazelnuts',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/Pr7Vi2H.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Roasted Hazelnuts',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000012',
			name: 'Raw Hazelnuts',
			slug: 'raw-hazelnuts',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/2ADiksE.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Hazelnuts',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000013',
			name: 'Roasted Pecans',
			slug: 'roasted-pecans',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/LbTGiMy.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Roasted Pecans',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000014',
			name: 'Raw Pine Nuts',
			slug: 'raw-pine-nuts',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/1ZY2nzB.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Pine Nuts',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000015',
			name: 'Roasted Pine Nuts',
			slug: 'roasted-pine-nuts',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/NTQZVMI.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Roasted Pine Nuts',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000016',
			name: 'Raw Walnuts',
			slug: 'raw-walnuts',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/0f2xrg3.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Walnuts',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000017',
			name: 'Raw Almonds',
			slug: 'raw-almonds',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/EQakQ7Q.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Almonds',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000018',
			name: 'Raw Pistachios',
			slug: 'raw-pistachios',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/04Vqk1B.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Pistachios',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000019',
			name: 'Dried Figs',
			slug: 'dried-figs',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/c66V2hL.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Dried Figs',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000020',
			name: 'Raw Cashews',
			slug: 'raw-cashews',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/WyTgOYu.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Cashews',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000021',
			name: 'Roasted Cashews',
			slug: 'roasted-cashews',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/PZhiBZ0.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Roasted Cashews',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000022',
			name: 'Raw Pumpkin Seeds',
			slug: 'raw-pumpkin-seeds',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/ItCUhhg.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Pumpkin Seeds',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000023',
			name: 'Roasted Pumpkin Seeds',
			slug: 'roasted-pumpkin-seeds',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/wKh9suT.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Roasted Pumpkin Seeds',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000024',
			name: 'Roasted Sunflower Seeds',
			slug: 'roasted-sunflower-seeds',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/IWTuaft.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Roasted Sunflower Seeds',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000025',
			name: 'Raw Sunflower Seeds',
			slug: 'raw-sunflower-seeds',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/94lrE1i.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Raw Sunflower Seeds',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000026',
			name: 'Red Quinoa',
			slug: 'red-quinoa',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/kxL5ATW.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Red Quinoa',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000027',
			name: 'White Quinoa',
			slug: 'white-quinoa',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/D38ErsW.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported White Quinoa',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000028',
			name: 'Bulghur - Coarse',
			slug: 'bulghur-coarse',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/5jM0vSK.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Bulghur - Coarse',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000029',
			name: 'Bulghur - Fine',
			slug: 'bulghur-fine',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/u4IeW7C.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Bulghur - Fine',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000030',
			name: 'Black Sesame - Roasted',
			slug: 'black-sesame-roasted',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/w44RPNH.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Black Sesame - Roasted',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000031',
			name: 'White Sesame - Roasted',
			slug: 'white-sesame-roasted',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/XV4W3ot.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported White Sesame - Roasted',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000032',
			name: 'Couscous',
			slug: 'couscous',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/ABRrw9y.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Couscous',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000033',
			name: 'Black Chia Seeds',
			slug: 'black-chia-seeds',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/QEeZx7a.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Black Chia Seeds',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000034',
			name: 'Alfalfa Seeds',
			slug: 'alfalfa-seeds',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/UNdHcSi.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Alfalfa Seeds',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000035',
			name: 'Basmati Rice',
			slug: 'basmati-rice',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/sYP6qkG.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Basmati Rice',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000036',
			name: 'Brown Flaxseeds',
			slug: 'brown-flaxseeds',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/Nlz7teN.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Brown Flaxseeds',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000037',
			name: 'Cannellini Beans',
			slug: 'cannellini-beans',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/mgasDfI.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Cannellini Beans',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000038',
			name: 'Coconut Flakes',
			slug: 'coconut-flakes',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/a856k1f.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Coconut Flakes',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000039',
			name: 'Desiccated Coconut',
			slug: 'desiccated-coconut',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/LqJqJqb.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Desiccated Coconut',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000040',
			name: 'Dried Orange Peels',
			slug: 'dried-orange-peels',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/nrNPRYm.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Dried Orange Peels',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000041',
			name: 'Gojiberries',
			slug: 'gojiberries',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/ThcUIqS.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Gojiberries',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000042',
			name: 'Golden Flaxseeds',
			slug: 'golden-flaxseeds',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/K7tOQqm.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Gojiberries',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000043',
			name: 'Golden Raisins - Jumbo',
			slug: 'golden-raisins-jumbo',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/vnVonhl.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Golden Raisins - Jumbo',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000044',
			name: 'Granola',
			slug: 'granola',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/lqHzJso.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Granola',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000045',
			name: 'Green Split Peas',
			slug: 'green-split-peas',
			categorySlug: 'spices',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/C1RTmlp.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Green Split Peas',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000046',
			name: 'Greenish Freekeh',
			slug: 'greenish-freekeh',
			categorySlug: 'spices',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/jljULjR.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Greenish Freekeh',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000047',
			name: 'Himalayan Salt',
			slug: 'himalayan-salt',
			categorySlug: 'spices',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/o42IeXa.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Himalayan Salt',
			isAvailable: true,
			isDiscount: true,
			discount: 10,
			isFeatured: false,
		},
		{
			id: 'omid-0000048',
			name: 'Mix Candied Fruit',
			slug: 'mix-candied-fruit',
			categorySlug: 'dried-fruits',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/KZmarAi.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Mix Candied Fruit',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000049',
			name: 'Pearl Barley',
			slug: 'pear-barley',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/MAviOuC.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Pearl Barley',
			isAvailable: true,
			isDiscount: true,
			discount: 20,
			isFeatured: false,
		},
		{
			id: 'omid-0000050',
			name: 'Quick Oat',
			slug: 'quick-oat',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/VZl2od8.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Quick Oat',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000051',
			name: 'Almond Slices - Raw',
			slug: 'almond-slices-raw',
			categorySlug: 'seeds',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/Za1lp9R.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Almond Slices - Raw',
			isAvailable: true,
			isDiscount: true,
			discount: 5,
			isFeatured: false,
		},
		{
			id: 'omid-0000052',
			name: 'Red Kidney Beans',
			slug: 'red-kidney-beans',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/fKQzteU.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Red Kidney Beans',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000053',
			name: 'Red Lentils',
			slug: 'red-lentils',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/rAktylN.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Red Lentils',
			isAvailable: true,
			isDiscount: true,
			discount: 15,
			isFeatured: false,
		},
		{
			id: 'omid-0000054',
			name: 'Rolled Oat',
			slug: 'rolled-oat',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/8feYTTL.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Rolled Oat',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: false,
		},
		{
			id: 'omid-0000055',
			name: 'Yellow Split Peas',
			slug: 'yellow-split-peas',
			categorySlug: 'nuts',
			quantity: [250, 500, 1000],
			price: [33000, 61000, 118000],
			stock: [10, 20, 30],
			brand: ['Omid Health Style', 'Blue Diamonds', 'Olam'],
			image: [
				'https://i.imgur.com/V6LB3vY.png',
				'https://i.imgur.com/roasted-walnuts2.jpeg',
				'https://i.imgur.com/roasted-walnuts3.jpeg',
			],
			description: 'Delicious imported Yellow Split Peas',
			isAvailable: true,
			isDiscount: false,
			discount: 25,
			isFeatured: true,
		},
	],
};

export default data;
