import React from 'react';
import Head from 'next/head';
import Navbar from './Navbar';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useSession } from 'next-auth/react';

const Layout = ({ children }) => {
	const { status, data: session } = useSession();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<ToastContainer position="bottom-center" limit={1} />
			<div className="flex min-h-screen flex-col justify-between text-white container mx-auto">
				<header className="sticky top-0 bg-[#1e1e1e] z-50">
					<Navbar status={status} session={session} />
				</header>
				<main>{children}</main>
				<footer className="flex justify-center items-center mt-auto text-sm">
					Copyright © 2022 Omid Health Style
				</footer>
			</div>
		</>
	);
};

export default Layout;
